from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_replyToOrdersDialog(object):
    def setupUi(self, replyToOrdersDialog):
        replyToOrdersDialog.setObjectName("replyToOrdersDialog")
        replyToOrdersDialog.resize(400, 278)
        self.label_14 = QtWidgets.QLabel(parent=replyToOrdersDialog)
        self.label_14.setGeometry(QtCore.QRect(10, 10, 101, 51))
        self.label_14.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_14.setObjectName("label_14")
        self.buyernameLineditReplyOrrdedialog = QtWidgets.QLineEdit(parent=replyToOrdersDialog)
        self.buyernameLineditReplyOrrdedialog.setGeometry(QtCore.QRect(130, 20, 261, 31))
        self.buyernameLineditReplyOrrdedialog.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.buyernameLineditReplyOrrdedialog.setReadOnly(True)
        self.buyernameLineditReplyOrrdedialog.setObjectName("buyernameLineditReplyOrrdedialog")
        self.label_15 = QtWidgets.QLabel(parent=replyToOrdersDialog)
        self.label_15.setGeometry(QtCore.QRect(10, 60, 101, 51))
        self.label_15.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_15.setObjectName("label_15")
        self.buyerphonelinedit_replydialog = QtWidgets.QLineEdit(parent=replyToOrdersDialog)
        self.buyerphonelinedit_replydialog.setGeometry(QtCore.QRect(130, 70, 261, 31))
        self.buyerphonelinedit_replydialog.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.buyerphonelinedit_replydialog.setReadOnly(True)
        self.buyerphonelinedit_replydialog.setObjectName("buyerphonelinedit_replydialog")
        self.label_16 = QtWidgets.QLabel(parent=replyToOrdersDialog)
        self.label_16.setGeometry(QtCore.QRect(10, 110, 101, 51))
        self.label_16.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_16.setObjectName("label_16")
        self.buyerlocation_replydialog = QtWidgets.QLineEdit(parent=replyToOrdersDialog)
        self.buyerlocation_replydialog.setGeometry(QtCore.QRect(130, 120, 261, 31))
        self.buyerlocation_replydialog.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.buyerlocation_replydialog.setReadOnly(True)
        self.buyerlocation_replydialog.setObjectName("buyerlocation_replydialog")
        self.label_17 = QtWidgets.QLabel(parent=replyToOrdersDialog)
        self.label_17.setGeometry(QtCore.QRect(10, 160, 131, 61))
        self.label_17.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_17.setObjectName("label_17")
        self.comboBox = QtWidgets.QComboBox(parent=replyToOrdersDialog)
        self.comboBox.setGeometry(QtCore.QRect(150, 170, 241, 31))
        self.comboBox.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.sendDeliveryMessagepushButton_replyDialog = QtWidgets.QPushButton(parent=replyToOrdersDialog)
        self.sendDeliveryMessagepushButton_replyDialog.setGeometry(QtCore.QRect(150, 230, 151, 28))
        self.sendDeliveryMessagepushButton_replyDialog.setObjectName("sendDeliveryMessagepushButton_replyDialog")

        self.retranslateUi(replyToOrdersDialog)
        QtCore.QMetaObject.connectSlotsByName(replyToOrdersDialog)

    def retranslateUi(self, replyToOrdersDialog):
        _translate = QtCore.QCoreApplication.translate
        replyToOrdersDialog.setWindowTitle(_translate("replyToOrdersDialog", "Send Delivery"))
        self.label_14.setText(_translate("replyToOrdersDialog", "Buyer Name"))
        self.label_15.setText(_translate("replyToOrdersDialog", "Buyer Phone"))
        self.label_16.setText(_translate("replyToOrdersDialog", "Location"))
        self.label_17.setText(_translate("replyToOrdersDialog", "Delivery Method"))
        self.comboBox.setItemText(0, _translate("replyToOrdersDialog", "Fargo"))
        self.comboBox.setItemText(1, _translate("replyToOrdersDialog", "Parcel"))
        self.comboBox.setItemText(2, _translate("replyToOrdersDialog", "Messenger"))
        self.comboBox.setItemText(3, _translate("replyToOrdersDialog", "BodaBoda"))
        self.sendDeliveryMessagepushButton_replyDialog.setText(_translate("replyToOrdersDialog", "Send Delivery Message"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    replyToOrdersDialog = QtWidgets.QDialog()
    ui = Ui_replyToOrdersDialog()
    ui.setupUi(replyToOrdersDialog)
    replyToOrdersDialog.show()
    sys.exit(app.exec())
