
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_buyerDashboardDialog(object):
    def setupUi(self, buyerDashboardDialog):
        buyerDashboardDialog.setObjectName("buyerDashboardDialog")
        buyerDashboardDialog.resize(954, 719)
        self.widget = QtWidgets.QWidget(parent=buyerDashboardDialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 261, 711))
        self.widget.setStyleSheet("background-color: rgb(31, 0, 93);")
        self.widget.setObjectName("widget")
        self.layoutWidget = QtWidgets.QWidget(parent=self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 10, 251, 681))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dashboardwidgetpushButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.dashboardwidgetpushButton.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.dashboardwidgetpushButton.setObjectName("dashboardwidgetpushButton")
        self.verticalLayout.addWidget(self.dashboardwidgetpushButton)
        self.browseproductspushbutton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.browseproductspushbutton.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.browseproductspushbutton.setObjectName("browseproductspushbutton")
        self.verticalLayout.addWidget(self.browseproductspushbutton)
        self.myorderspushbutton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.myorderspushbutton.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.myorderspushbutton.setObjectName("myorderspushbutton")
        self.verticalLayout.addWidget(self.myorderspushbutton)
        self.cartpushbutton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.cartpushbutton.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.cartpushbutton.setObjectName("cartpushbutton")
        self.verticalLayout.addWidget(self.cartpushbutton)
        self.paymentpushbutton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.paymentpushbutton.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.paymentpushbutton.setObjectName("paymentpushbutton")
        self.verticalLayout.addWidget(self.paymentpushbutton)
        self.profilepushbutton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.profilepushbutton.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.profilepushbutton.setObjectName("profilepushbutton")
        self.verticalLayout.addWidget(self.profilepushbutton)
        self.settingspushbutton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.settingspushbutton.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.settingspushbutton.setObjectName("settingspushbutton")
        self.verticalLayout.addWidget(self.settingspushbutton)
        self.logoutbutton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.logoutbutton.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.logoutbutton.setObjectName("logoutbutton")
        self.verticalLayout.addWidget(self.logoutbutton)
        self.widget_2 = QtWidgets.QWidget(parent=buyerDashboardDialog)
        self.widget_2.setGeometry(QtCore.QRect(260, 0, 691, 711))
        self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget_2.setObjectName("widget_2")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.widget_2)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 671, 701))
        self.stackedWidget.setObjectName("stackedWidget")
        self.dashboardpage = QtWidgets.QWidget()
        self.dashboardpage.setObjectName("dashboardpage")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.dashboardpage)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 0, 361, 231))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_26 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_26.setGeometry(QtCore.QRect(10, 30, 81, 16))
        self.label_26.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;")
        self.label_26.setObjectName("label_26")
        self.totalorderslcdNumber = QtWidgets.QLCDNumber(parent=self.groupBox_3)
        self.totalorderslcdNumber.setGeometry(QtCore.QRect(10, 60, 64, 31))
        self.totalorderslcdNumber.setObjectName("totalorderslcdNumber")
        self.label_27 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_27.setGeometry(QtCore.QRect(150, 30, 121, 16))
        self.label_27.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;")
        self.label_27.setObjectName("label_27")
        self.ordersInCartLCDnumber = QtWidgets.QLCDNumber(parent=self.groupBox_3)
        self.ordersInCartLCDnumber.setGeometry(QtCore.QRect(160, 60, 64, 31))
        self.ordersInCartLCDnumber.setObjectName("ordersInCartLCDnumber")
        self.label_28 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_28.setGeometry(QtCore.QRect(10, 120, 111, 16))
        self.label_28.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;")
        self.label_28.setObjectName("label_28")
        self.cancelledordersLCDdisplay = QtWidgets.QLCDNumber(parent=self.groupBox_3)
        self.cancelledordersLCDdisplay.setGeometry(QtCore.QRect(10, 140, 64, 31))
        self.cancelledordersLCDdisplay.setObjectName("cancelledordersLCDdisplay")
        self.groupBox_4 = QtWidgets.QGroupBox(parent=self.dashboardpage)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 240, 361, 231))
        self.groupBox_4.setObjectName("groupBox_4")
        self.settingscommandLinkButton_dashboard = QtWidgets.QCommandLinkButton(parent=self.groupBox_4)
        self.settingscommandLinkButton_dashboard.setGeometry(QtCore.QRect(10, 20, 222, 48))
        self.settingscommandLinkButton_dashboard.setObjectName("settingscommandLinkButton_dashboard")
        self.profilecommandLinkButton = QtWidgets.QCommandLinkButton(parent=self.groupBox_4)
        self.profilecommandLinkButton.setGeometry(QtCore.QRect(10, 80, 222, 48))
        self.profilecommandLinkButton.setObjectName("profilecommandLinkButton")
        self.cartCommandlinkbutton = QtWidgets.QCommandLinkButton(parent=self.groupBox_4)
        self.cartCommandlinkbutton.setGeometry(QtCore.QRect(10, 140, 222, 48))
        self.cartCommandlinkbutton.setObjectName("cartCommandlinkbutton")
        self.label_2 = QtWidgets.QLabel(parent=self.dashboardpage)
        self.label_2.setGeometry(QtCore.QRect(30, 680, 271, 21))
        self.label_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.dashboardpage)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 480, 361, 181))
        self.groupBox_2.setObjectName("groupBox_2")
        self.helpandsupporttextEdit = QtWidgets.QTextEdit(parent=self.groupBox_2)
        self.helpandsupporttextEdit.setGeometry(QtCore.QRect(0, 10, 361, 171))
        self.helpandsupporttextEdit.setObjectName("helpandsupporttextEdit")
        self.stackedWidget.addWidget(self.dashboardpage)
        self.browseproductspage = QtWidgets.QWidget()
        self.browseproductspage.setObjectName("browseproductspage")
        self.browseproductsTableWidget = QtWidgets.QTableWidget(parent=self.browseproductspage)
        self.browseproductsTableWidget.setGeometry(QtCore.QRect(0, 10, 681, 411))
        self.browseproductsTableWidget.setObjectName("browseproductsTableWidget")
        self.browseproductsTableWidget.setColumnCount(6)
        self.browseproductsTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.browseproductsTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.browseproductsTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.browseproductsTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.browseproductsTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.browseproductsTableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.browseproductsTableWidget.setHorizontalHeaderItem(5, item)
        self.label_12 = QtWidgets.QLabel(parent=self.browseproductspage)
        self.label_12.setGeometry(QtCore.QRect(10, 460, 241, 21))
        self.label_12.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_12.setObjectName("label_12")
        self.searchproductLinedit = QtWidgets.QLineEdit(parent=self.browseproductspage)
        self.searchproductLinedit.setGeometry(QtCore.QRect(260, 460, 331, 22))
        self.searchproductLinedit.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.searchproductLinedit.setObjectName("searchproductLinedit")
        self.stackedWidget.addWidget(self.browseproductspage)
        self.myorderspage = QtWidgets.QWidget()
        self.myorderspage.setObjectName("myorderspage")
        self.browseproductsTableWidget_2 = QtWidgets.QTableWidget(parent=self.myorderspage)
        self.browseproductsTableWidget_2.setGeometry(QtCore.QRect(0, 10, 681, 411))
        self.browseproductsTableWidget_2.setObjectName("browseproductsTableWidget_2")
        self.browseproductsTableWidget_2.setColumnCount(4)
        self.browseproductsTableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.browseproductsTableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.browseproductsTableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.browseproductsTableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.browseproductsTableWidget_2.setHorizontalHeaderItem(3, item)
        self.stackedWidget.addWidget(self.myorderspage)
        self.cartpage = QtWidgets.QWidget()
        self.cartpage.setObjectName("cartpage")
        self.cart_table_Widget = QtWidgets.QTableWidget(parent=self.cartpage)
        self.cart_table_Widget.setGeometry(QtCore.QRect(0, 10, 681, 411))
        self.cart_table_Widget.setObjectName("cart_table_Widget")
        self.cart_table_Widget.setColumnCount(5)
        self.cart_table_Widget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.cart_table_Widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cart_table_Widget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cart_table_Widget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.cart_table_Widget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.cart_table_Widget.setHorizontalHeaderItem(4, item)
        self.productsinCartLabel = QtWidgets.QLabel(parent=self.cartpage)
        self.productsinCartLabel.setGeometry(QtCore.QRect(20, 470, 181, 20))
        self.productsinCartLabel.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.productsinCartLabel.setObjectName("productsinCartLabel")
        self.stackedWidget.addWidget(self.cartpage)
        self.paymentspage = QtWidgets.QWidget()
        self.paymentspage.setObjectName("paymentspage")
        self.cart_table_Widget_2 = QtWidgets.QTableWidget(parent=self.paymentspage)
        self.cart_table_Widget_2.setGeometry(QtCore.QRect(0, 10, 681, 411))
        self.cart_table_Widget_2.setObjectName("cart_table_Widget_2")
        self.cart_table_Widget_2.setColumnCount(3)
        self.cart_table_Widget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.cart_table_Widget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.cart_table_Widget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.cart_table_Widget_2.setHorizontalHeaderItem(2, item)
        self.totalmoneyspentLabel_paymentpagelabel = QtWidgets.QLabel(parent=self.paymentspage)
        self.totalmoneyspentLabel_paymentpagelabel.setGeometry(QtCore.QRect(10, 450, 171, 20))
        self.totalmoneyspentLabel_paymentpagelabel.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.totalmoneyspentLabel_paymentpagelabel.setObjectName("totalmoneyspentLabel_paymentpagelabel")
        self.stackedWidget.addWidget(self.paymentspage)
        self.profilepage = QtWidgets.QWidget()
        self.profilepage.setObjectName("profilepage")
        self.groupBox = QtWidgets.QGroupBox(parent=self.profilepage)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 431, 251))
        self.groupBox.setObjectName("groupBox")
        self.label_19 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_19.setGeometry(QtCore.QRect(10, 40, 51, 20))
        self.label_19.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_20.setGeometry(QtCore.QRect(10, 80, 71, 20))
        self.label_20.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_21.setGeometry(QtCore.QRect(10, 120, 71, 20))
        self.label_21.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_21.setObjectName("label_21")
        self.namelineEdit_seettingspage = QtWidgets.QLineEdit(parent=self.groupBox)
        self.namelineEdit_seettingspage.setGeometry(QtCore.QRect(90, 40, 331, 22))
        self.namelineEdit_seettingspage.setObjectName("namelineEdit_seettingspage")
        self.locationlineEdit_seettingspage_2 = QtWidgets.QLineEdit(parent=self.groupBox)
        self.locationlineEdit_seettingspage_2.setGeometry(QtCore.QRect(90, 80, 331, 22))
        self.locationlineEdit_seettingspage_2.setObjectName("locationlineEdit_seettingspage_2")
        self.phoneNoineEdit_seettingspage_2 = QtWidgets.QLineEdit(parent=self.groupBox)
        self.phoneNoineEdit_seettingspage_2.setGeometry(QtCore.QRect(90, 120, 331, 22))
        self.phoneNoineEdit_seettingspage_2.setObjectName("phoneNoineEdit_seettingspage_2")
        self.updateprofilebutton = QtWidgets.QPushButton(parent=self.groupBox)
        self.updateprofilebutton.setGeometry(QtCore.QRect(320, 160, 93, 28))
        self.updateprofilebutton.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.updateprofilebutton.setObjectName("updateprofilebutton")
        self.stackedWidget.addWidget(self.profilepage)
        self.settingspage = QtWidgets.QWidget()
        self.settingspage.setObjectName("settingspage")
        self.accountsettingsgroupBox = QtWidgets.QGroupBox(parent=self.settingspage)
        self.accountsettingsgroupBox.setGeometry(QtCore.QRect(10, 10, 371, 251))
        self.accountsettingsgroupBox.setObjectName("accountsettingsgroupBox")
        self.label_22 = QtWidgets.QLabel(parent=self.accountsettingsgroupBox)
        self.label_22.setGeometry(QtCore.QRect(10, 30, 131, 16))
        self.label_22.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(parent=self.accountsettingsgroupBox)
        self.label_23.setGeometry(QtCore.QRect(10, 60, 91, 16))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(parent=self.accountsettingsgroupBox)
        self.label_24.setGeometry(QtCore.QRect(10, 100, 91, 16))
        self.label_24.setObjectName("label_24")
        self.oldpasswordlineEdit_settings = QtWidgets.QLineEdit(parent=self.accountsettingsgroupBox)
        self.oldpasswordlineEdit_settings.setGeometry(QtCore.QRect(110, 60, 221, 22))
        self.oldpasswordlineEdit_settings.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.oldpasswordlineEdit_settings.setObjectName("oldpasswordlineEdit_settings")
        self.newpasswordlinedit_settings = QtWidgets.QLineEdit(parent=self.accountsettingsgroupBox)
        self.newpasswordlinedit_settings.setGeometry(QtCore.QRect(110, 100, 221, 22))
        self.newpasswordlinedit_settings.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.newpasswordlinedit_settings.setObjectName("newpasswordlinedit_settings")
        self.changePasswordpushButton = QtWidgets.QPushButton(parent=self.accountsettingsgroupBox)
        self.changePasswordpushButton.setGeometry(QtCore.QRect(110, 150, 93, 28))
        self.changePasswordpushButton.setObjectName("changePasswordpushButton")
        self.stackedWidget.addWidget(self.settingspage)

        self.retranslateUi(buyerDashboardDialog)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(buyerDashboardDialog)

    def retranslateUi(self, buyerDashboardDialog):
        _translate = QtCore.QCoreApplication.translate
        buyerDashboardDialog.setWindowTitle(_translate("buyerDashboardDialog", "Buyer-Agrimesh Company"))
        self.dashboardwidgetpushButton.setText(_translate("buyerDashboardDialog", "Dashboard"))
        self.browseproductspushbutton.setText(_translate("buyerDashboardDialog", "Browse Products"))
        self.myorderspushbutton.setText(_translate("buyerDashboardDialog", "My Orders"))
        self.cartpushbutton.setText(_translate("buyerDashboardDialog", "Cart"))
        
        self.cartpushbutton.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(3))
        self.myorderspushbutton.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(2))
        self.paymentpushbutton.setText(_translate("buyerDashboardDialog", "Payment"))
        self.profilepushbutton.setText(_translate("buyerDashboardDialog", "Profile"))
        self.settingspushbutton.setText(_translate("buyerDashboardDialog", "Settings"))
        self.logoutbutton.setText(_translate("buyerDashboardDialog", "Logout"))
        self.groupBox_3.setTitle(_translate("buyerDashboardDialog", "Key Metrics"))
        self.label_26.setText(_translate("buyerDashboardDialog", "Total orders"))
        self.label_27.setText(_translate("buyerDashboardDialog", "orders in Cart"))
        self.label_28.setText(_translate("buyerDashboardDialog", "Cancelled Orders"))
        self.groupBox_4.setTitle(_translate("buyerDashboardDialog", "Quick Actions"))
        self.settingscommandLinkButton_dashboard.setText(_translate("buyerDashboardDialog", "Settings"))
        self.profilecommandLinkButton.setText(_translate("buyerDashboardDialog", "profile"))
        self.cartCommandlinkbutton.setText(_translate("buyerDashboardDialog", "Cart"))
        self.label_2.setText(_translate("buyerDashboardDialog", "WE ARE PROUD TO SERVE YOU"))
        self.groupBox_2.setTitle(_translate("buyerDashboardDialog", "HELP AND SUPPORT"))
        item = self.browseproductsTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("buyerDashboardDialog", "Product Name"))
        item = self.browseproductsTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("buyerDashboardDialog", "Category"))
        item = self.browseproductsTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("buyerDashboardDialog", "Quantity"))
        item = self.browseproductsTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("buyerDashboardDialog", "Price"))
        item = self.browseproductsTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("buyerDashboardDialog", "Location"))
        item = self.browseproductsTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("buyerDashboardDialog", "Action"))
        self.label_12.setText(_translate("buyerDashboardDialog", "Search Your Preffered Product"))
        self.searchproductLinedit.setPlaceholderText(_translate("buyerDashboardDialog", "Type some words"))
        item = self.browseproductsTableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("buyerDashboardDialog", "Product Name"))
        item = self.browseproductsTableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("buyerDashboardDialog", "Quantity"))
        item = self.browseproductsTableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("buyerDashboardDialog", "Price"))
        item = self.browseproductsTableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("buyerDashboardDialog", "Action"))
        item = self.cart_table_Widget.horizontalHeaderItem(0)
        item.setText(_translate("buyerDashboardDialog", "Product Name"))
        item = self.cart_table_Widget.horizontalHeaderItem(1)
        item.setText(_translate("buyerDashboardDialog", "Quantity"))
        item = self.cart_table_Widget.horizontalHeaderItem(2)
        item.setText(_translate("buyerDashboardDialog", "Price"))
        item = self.cart_table_Widget.horizontalHeaderItem(3)
        item.setText(_translate("buyerDashboardDialog", "Action 1"))
        item = self.cart_table_Widget.horizontalHeaderItem(4)
        item.setText(_translate("buyerDashboardDialog", "Action 2"))
        self.productsinCartLabel.setText(_translate("buyerDashboardDialog", "Products in The Cart: "))
        item = self.cart_table_Widget_2.horizontalHeaderItem(0)
        item.setText(_translate("buyerDashboardDialog", "Product Name"))
        item = self.cart_table_Widget_2.horizontalHeaderItem(1)
        item.setText(_translate("buyerDashboardDialog", "Quantity"))
        item = self.cart_table_Widget_2.horizontalHeaderItem(2)
        item.setText(_translate("buyerDashboardDialog", "Price"))
        self.totalmoneyspentLabel_paymentpagelabel.setText(_translate("buyerDashboardDialog", "Total money Spent: "))
        self.groupBox.setTitle(_translate("buyerDashboardDialog", "Personal info"))
        self.label_19.setText(_translate("buyerDashboardDialog", "Name"))
        self.label_20.setText(_translate("buyerDashboardDialog", "Location"))
        self.label_21.setText(_translate("buyerDashboardDialog", "PhoneNo."))
        self.updateprofilebutton.setText(_translate("buyerDashboardDialog", "Update"))
        self.accountsettingsgroupBox.setTitle(_translate("buyerDashboardDialog", "Account Settings"))
        self.label_22.setText(_translate("buyerDashboardDialog", "Change Password"))
        self.label_23.setText(_translate("buyerDashboardDialog", "Old Password"))
        self.label_24.setText(_translate("buyerDashboardDialog", "New Password"))
        self.changePasswordpushButton.setText(_translate("buyerDashboardDialog", "Change"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    buyerDashboardDialog = QtWidgets.QDialog()
    ui = Ui_buyerDashboardDialog()
    ui.setupUi(buyerDashboardDialog)
    buyerDashboardDialog.show()
    sys.exit(app.exec())
